---

# Editor CLI predeterminado
cli_editor: "nvim"            # opciones: nvim | vim

# Editor GUI (VSCodium) – instala por defecto
install_vscodium: true
vscodium_flatpak_id: "com.vscodium.codium"

container_runtime: "podman"     # opciones: podman | docker
install_gaming: true
install_ai: true
dotfiles_packages:
  - bash
  - git
  - vim
  - tmux

# Usuario workstation por defecto:
# - Si se ejecuta con sudo: SUDO_USER
# - Si no, ansible_user_id
workstation_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

# HOME del usuario (por si falla la resolución automática)
# Se sobreescribe en pre_tasks vía getent (ver site.yml)
workstation_home: >-
  {{ '/root' if workstation_user == 'root'
  else '/home/' + workstation_user }}


# ===== VeraCrypt (instalación .deb oficial con verificación PGP) =====
veracrypt_version: "1.26.24"            # la que tengas fijada
veracrypt_series: "22.04"               # Pop!_OS 22.04 base Ubuntu 22.04
veracrypt_arch: "amd64"

# URLs: los .deb se publican en Launchpad y están enlazados desde Downloads
veracrypt_deb_url: >-
  "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/ve
  racrypt-{{ veracrypt_version }}-Ubuntu
  -{{ veracrypt_series }}-{{ veracrypt_arch }}.deb"
veracrypt_sig_url: >-
  "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/ver
  acrypt-{{ veracrypt_version }}-Ubunt
  u-{{ veracrypt_series }}-{{ veracrypt_arch }}.deb.sig"

# Clave PGP oficial (actual): ID 0x680D16DE,
# fingerprint 5069A233D55A0EEB174A5FC3821ACD02680D16DE
veracrypt_pgp_key_url: >-
  "https://amcrypto.jp/VeraCrypt/VeraCrypt_PGP_public_key.asc"

# Contenedores a montar con el wrapper "vc"
veracrypt_containers:
  - name: "personal"
    path: >-
      "/home/{{ workstation_user }}/
      Documents/CONTENEDOR/SECURE/baul_desmuntat"
    mount: "/home/{{ workstation_user }}/Documents/SECURE_veracrypt/"
    pim: ""    # si usas PIM, pon el número; vacío si no
