creation_rules:
  - path_regex: secrets/.*\.sops\.ya?ml$
    encrypted_regex: '^(wg_conf|data|stringData|.*_secret|secrets|tokens)$'
    age: "age1gg6nqp6hd5djvedvtrpr60wrtdqyqekcxkcynlvhqpq77qeqgcgqhevcff"
  - path_regex: secrets/.*\.sops$        # ⬅️ binarios (clave privada)
    age: "age1gg6nqp6hd5djvedvtrpr60wrtdqyqekcxkcynlvhqpq77qeqgcgqhevcff"
  - path_regex: ^group_vars/.*\.sops\.ya?ml$  #⬅️  Ficheros dentro de group_vars
    age: "age1gg6nqp6hd5djvedvtrpr60wrtdqyqekcxkcynlvhqpq77qeqgcgqhevcff"
