---
- name: "PopOS Workstation"
  hosts: all
  become: true

  # Variables cifradas globales (opcional si está vacío)
  vars_files:
    - secrets/vars.sops.yaml      # cifrado con SOPS (opcional si vacío)

  roles:
    # Aquest primer es necesari, ja que carrega variables
    # com el usuari i uid del usuari que llança el playbook
    - {role: workstation_facts, tags: ['always']}

    # Roles opcionals
    - {role: base, tags: ['base']}
    - {role: devtools, tags: ['dev']}
    - {role: containers, tags: ['containers']}
    - {role: gaming, when: install_gaming, tags: ['gaming']}
    - {role: ai, when: install_ai, tags: ['ai']}
    - {role: security, tags: ['security']}
    - {role: ssh, tags: ['ssh']}
    - {role: storage_exfat, tags: ['exfat']}
    - {role: security_veracrypt, tags: ['veracrypt']}
    - {role: network_dnsdot, tags: ['network', 'dns', 'dot']}
    - {role: network_wg_protonvpn, tags: ['network', 'wg', 'vpn', 'protonvpn']}
    - {role: mm_media, tags: ['media', 'containers', 'pipeviewer']}
