all:
  children:
    workstations:
      hosts:
        ws01.example.lan:
          ansible_user: pops
          ansible_become: true
          ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
