---
- name: Cargar vars según familia de SO
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: Instalar Podman (rootless)
  when: container_runtime == "podman"
  ansible.builtin.package:
    name: "{{ containers_podman_packages }}"
    state: present
  tags: ['containers']

- name: Instalar Docker
  when: container_runtime == "docker"
  ansible.builtin.package:
    name: "{{ containers_docker_packages }}"
    state: present
  tags: ['containers']

- name: "Añadir usuario al grupo docker ({{ workstation_user }})"
  when: container_runtime == "docker"
  become: true
  ansible.builtin.user:
    name: "{{ workstation_user }}"
    groups: docker
    append: true
  tags: ['containers']

- name: NVIDIA Container Toolkit (GPU opcional)
  ansible.builtin.package:
    name: "{{ containers_nvidia_toolkit_packages }}"
    state: present
  tags: ['containers', 'ai']

# Nota GPU con Podman: si usas GPU, al ejecutar contenedores añade
# --hooks-dir=/usr/share/containers/oci/hooks.d/ cuando sea necesario.
# Mantengo esto simple y estable.
