---
- name: "DEBUG: ver network_wg_protonvpn_instances cruda"
  ansible.builtin.debug:
    var: network_wg_protonvpn_instances
  tags: [always]

- name: "DEBUG: claves presentes en cada item"
  ansible.builtin.debug:
    msg:
      name: "{{ item.name | default('sin_name') }}"
      keys: "{{ item.keys() | list }}"
      types: "{{ item | type_debug }}"
  loop: "{{ network_wg_protonvpn_instances | default([]) }}"
  loop_control: {label: "{{ item.name | default('sin_name') }}"}
  tags: [always]

- name: "Resumen del plan de despliegue"
  ansible.builtin.debug:
    msg:
      name: "{{ item.name }}"
      autostart: "{{ item.autostart }}"
      wg_conf_sops: "{{ item.wg_conf_sops }}"
      wg_if: "{{ item.wg_if }}"
      netns: "{{ item.name }}"
      subnet_p2p: "{{ item.subnet_p2p }}"
      host_ip: "{{ item.host_ip }}"
      ns_ip: "{{ item.ns_ip }}"
      dns_ns: "{{ item.dns_ns | default('usará DNS del conf') }}"
      wan_if: "{{ item.wan_if | default('auto') }}"
      endpoint_override: "{{ item.endpoint_override | default('') }}"
  loop: "{{ network_wg_protonvpn_instances }}"
  loop_control:
    label: "{{ item.name }}"
