---
name: ansible-lint
"on": [push, pull_request]
permissions: {contents: read}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}

      - name: Install ansible-lint via pip
        run: python -m pip install --upgrade pip && pip install ansible-lint

      - uses: actions/cache@v4
        with:
          path: |
            ~/.ansible/collections
            ~/.cache/ansible-lint
          key: >
            collections-${{ runner.os }}-${{
            hashFiles('**/collections/requirements.yml',
                      '**/requirements.yml') }}
          restore-keys: |
            collections-${{ runner.os }}-

      - name: Install Galaxy collections (with retries)
        if: >
          hashFiles('collections/requirements.yml') != '' ||
          hashFiles('requirements.yml') != ''
        run: |
          set -euo pipefail
          req=""
          if [ -f collections/requirements.yml ]; then
            req=collections/requirements.yml;
          fi
          if [ -z "$req" ] && [ -f requirements.yml ]; then
            req=requirements.yml;
          fi
          for i in 1 2 3; do
            ansible-galaxy collection install -r "$req" && break || {
              echo "Retry $i/3 ..."; sleep $((i*20));
            }
          done

      - name: ansible-lint (offline)
        env:
          # por si tu ansible.cfg no está en raíz:
          ANSIBLE_COLLECTIONS_PATHS: >-
            ~/.ansible/collections:/usr/share/ansible/collections
        run: ansible-lint --offline -p --profile production
